# Pin assignments for Stepper X, Y, Z motors
STEP_PIN_X = 28
DIR_PIN_X = 27
ENABLE_PIN_X = 29
STOPPER_PIN_X = 1

STEP_PIN_Y = 15
DIR_PIN_Y = 14
ENABLE_PIN_Y = 26
STOPPER_PIN_Y = 2

STEP_PIN_Z = 7
DIR_PIN_Z = 6
ENABLE_PIN_Z = 8
STOPPER_PIN_Z = 3

# I2C Pins
SCL_PIN = 5
SDA_PIN = 4

# Sensors
MOISTURE_SENSOR_1_PIN = 32
MOISTURE_SENSOR_2_PIN = 33
TEMPERATURE_SENSOR_PIN = 34
HUMIDITY_SENSOR_PIN = 35
LIGHT_SENSOR_PIN = 36

# Relays
SOLENOID_RELAY_PIN = 2

# Buttons
FORCE_STOP = 13